bin: Clarify terminology type in chmod-default

diff --git a/bin/chmod-default b/bin/chmod-default
--- a/bin/chmod-default
+++ b/bin/chmod-default
@@ -48,6 +48,6 @@ if [[ -f ${ARGS[FILE]} ]]; then
 elif [[ -d ${ARGS[FILE]} ]]; then
   chmod '=rwx' "${ARGS[FILE]}"
 else
-  >&2 echo "Error: Node type is not supported."
+  >&2 echo 'Error: inode type is not supported.'
   exit 1
 fi
