bin: Use full stop in all error messages

diff --git a/bin/chmod-default b/bin/chmod-default
--- a/bin/chmod-default
+++ b/bin/chmod-default
@@ -25,6 +25,6 @@ if [[ -f "${ARGS[FILE]}" ]]; then
 elif [[ -d "${ARGS[FILE]}" ]]; then
   chmod '=rwx' "${ARGS[FILE]}"
 else
-  >&2 echo "Error: Unsupported node type"
+  >&2 echo "Error: Node type is not supported."
   exit 1
 fi
diff --git a/bin/npm-show-scripts b/bin/npm-show-scripts
--- a/bin/npm-show-scripts
+++ b/bin/npm-show-scripts
@@ -21,7 +21,7 @@ EOF
 )"
 
 if [[ ! -f package.json ]]; then
-  >&2 echo 'Error: package.json not found'
+  >&2 echo 'Error: Cannot find file "package.json".'
   exit 1
 fi
 
