bin: Use "FATAL ERROR" for errors that exit

diff --git a/bin/create-script b/bin/create-script
--- a/bin/create-script
+++ b/bin/create-script
@@ -83,7 +83,7 @@ EOF
 )"
 
 if [[ -f "${ARGS[FILE]}" ]]; then
-  >&2 echo "Error: File \"${ARGS[FILE]}\" already exists."
+  >&2 echo "FATAL ERROR: File \"${ARGS[FILE]}\" already exists."
   exit 1
 fi
 
diff --git a/bin/device b/bin/device
--- a/bin/device
+++ b/bin/device
@@ -80,6 +80,6 @@ EOF
 if OUTPUT=$(findmnt --noheadings --output SOURCE --mountpoint "${ARGS[MOUNTPOINT]}"); then
   echo "$OUTPUT"
 else
-  >&2 echo "Error: ${ARGS[MOUNTPOINT]} is not a mountpoint."
+  >&2 echo "FATAL ERROR: ${ARGS[MOUNTPOINT]} is not a mountpoint."
   exit 1
 fi
diff --git a/bin/full-backup b/bin/full-backup
--- a/bin/full-backup
+++ b/bin/full-backup
@@ -79,7 +79,7 @@ EOF
 )"
 
 if [[ ! -d "${ARGS[DIRECTORY]}" ]]; then
-  >&2 echo "Error: Directory \"${ARGS[DIRECTORY]}\" does not exist."
+  >&2 echo "FATAL ERROR: Directory \"${ARGS[DIRECTORY]}\" does not exist."
   exit 1
 fi
 
diff --git a/bin/indent b/bin/indent
--- a/bin/indent
+++ b/bin/indent
@@ -88,7 +88,7 @@ EOF
 )"
 
 if [[ ! ${ARGS[--size]} =~ ^[0-9]+$ ]]; then
-  >&2 echo 'Error: Indent size must be a non-negative integer.'
+  >&2 echo 'FATAL ERROR: Indent size must be a non-negative integer.'
   exit 1
 fi
 
diff --git a/bin/rsync-mirror-local b/bin/rsync-mirror-local
--- a/bin/rsync-mirror-local
+++ b/bin/rsync-mirror-local
@@ -89,7 +89,7 @@ SOURCE_WITH_TRAILING_SLASH=$SOURCE_WITH_NO_TRAILING_SLASH/
 TARGET_WITH_TRAILING_SLASH=$TARGET_WITH_NO_TRAILING_SLASH/
 
 if [[ ! -d "$SOURCE_WITH_TRAILING_SLASH" ]]; then
-    >&2 echo "Error: \"$SOURCE_WITH_TRAILING_SLASH\" does not exist."
+    >&2 echo "FATAL ERROR: \"$SOURCE_WITH_TRAILING_SLASH\" does not exist."
     exit 1
 fi
 
@@ -103,7 +103,7 @@ fi
 # Perhaps this behavior, checking whether the destination directory exists, can
 # be made an option in the future, disabled by default.
 if [[ ! -d "$TARGET_WITH_TRAILING_SLASH" ]]; then
-    >&2 echo "Error: \"$TARGET_WITH_TRAILING_SLASH\" does not exist."
+    >&2 echo "FATAL ERROR: \"$TARGET_WITH_TRAILING_SLASH\" does not exist."
     exit 1
 fi
 
