bin: Standardize, expand warnings about deps

diff --git a/bin/entr-fzf b/bin/entr-fzf
--- a/bin/entr-fzf
+++ b/bin/entr-fzf
@@ -47,15 +47,17 @@ Options:
 EOF
 )"
 
-if ! command -v entr > /dev/null; then
-  >&2 echo 'Error: entr is not installed.'
-  exit 1
-fi
+DEPENDENCIES=(
+  entr
+  fzf
+)
 
-if ! command -v fzf > /dev/null; then
-  >&2 echo 'Error: fzf is not installed.'
-  exit 1
-fi
+for DEPENDENCY in "${DEPENDENCIES[@]}"; do
+  if ! command -v "$DEPENDENCY" > /dev/null; then
+    >&2 echo "Error: \"$DEPENDENCY\" is not installed."
+    exit 1
+  fi
+done
 
 # Process variadic arguments.
 #
diff --git a/bin/git-upstream b/bin/git-upstream
--- a/bin/git-upstream
+++ b/bin/git-upstream
@@ -52,6 +52,17 @@ Options:
 EOF
 )"
 
+DEPENDENCIES=(
+  git
+)
+
+for DEPENDENCY in "${DEPENDENCIES[@]}"; do
+  if ! command -v "$DEPENDENCY" > /dev/null; then
+    >&2 echo "Error: \"$DEPENDENCY\" is not installed."
+    exit 1
+  fi
+done
+
 # This script is based on the following Stack Overflow answer:
 # https://stackoverflow.com/a/9753364/715866
 
diff --git a/bin/npm-show-scripts b/bin/npm-show-scripts
--- a/bin/npm-show-scripts
+++ b/bin/npm-show-scripts
@@ -43,6 +43,17 @@ Options:
 EOF
 )"
 
+DEPENDENCIES=(
+  jq
+)
+
+for DEPENDENCY in "${DEPENDENCIES[@]}"; do
+  if ! command -v "$DEPENDENCY" > /dev/null; then
+    >&2 echo "Error: \"$DEPENDENCY\" is not installed."
+    exit 1
+  fi
+done
+
 if [[ ! -f package.json ]]; then
   >&2 echo 'Error: Cannot find file "package.json".'
   exit 1
diff --git a/bin/npm-show-version-latest b/bin/npm-show-version-latest
--- a/bin/npm-show-version-latest
+++ b/bin/npm-show-version-latest
@@ -42,4 +42,15 @@ Options:
 EOF
 )"
 
+DEPENDENCIES=(
+  npm
+)
+
+for DEPENDENCY in "${DEPENDENCIES[@]}"; do
+  if ! command -v "$DEPENDENCY" > /dev/null; then
+    >&2 echo "Error: \"$DEPENDENCY\" is not installed."
+    exit 1
+  fi
+done
+
 npm show "${ARGS[PACKAGE]}" version
diff --git a/bin/npm-upgrade-packages b/bin/npm-upgrade-packages
--- a/bin/npm-upgrade-packages
+++ b/bin/npm-upgrade-packages
@@ -45,6 +45,18 @@ Options:
 EOF
 )"
 
+DEPENDENCIES=(
+  npm
+  npx
+)
+
+for DEPENDENCY in "${DEPENDENCIES[@]}"; do
+  if ! command -v "$DEPENDENCY" > /dev/null; then
+    >&2 echo "Error: \"$DEPENDENCY\" is not installed."
+    exit 1
+  fi
+done
+
 if [[ "${ARGS[--from-scratch]}" ]]; then
   rm -rf node_modules package-lock.json
 fi
diff --git a/bin/overwrite-csv-double-quoting-all-values b/bin/overwrite-csv-double-quoting-all-values
--- a/bin/overwrite-csv-double-quoting-all-values
+++ b/bin/overwrite-csv-double-quoting-all-values
@@ -42,6 +42,17 @@ Options:
 EOF
 )"
 
+DEPENDENCIES=(
+  ruby
+)
+
+for DEPENDENCY in "${DEPENDENCIES[@]}"; do
+  if ! command -v "$DEPENDENCY" > /dev/null; then
+    >&2 echo "Error: \"$DEPENDENCY\" is not installed."
+    exit 1
+  fi
+done
+
 NEW_FILE=$(mktemp)
 
 # Use Ruby to correctly handle CSV files that already double-quote values, CSV
diff --git a/bin/overwrite-csv-with-fputcsv b/bin/overwrite-csv-with-fputcsv
--- a/bin/overwrite-csv-with-fputcsv
+++ b/bin/overwrite-csv-with-fputcsv
@@ -51,6 +51,17 @@ Options:
 EOF
 )"
 
+DEPENDENCIES=(
+  php
+)
+
+for DEPENDENCY in "${DEPENDENCIES[@]}"; do
+  if ! command -v "$DEPENDENCY" > /dev/null; then
+    >&2 echo "Error: \"$DEPENDENCY\" is not installed."
+    exit 1
+  fi
+done
+
 php <<EOF
 <?php
 
diff --git a/bin/overwrite-with-github-template b/bin/overwrite-with-github-template
--- a/bin/overwrite-with-github-template
+++ b/bin/overwrite-with-github-template
@@ -50,6 +50,18 @@ Options:
 EOF
 )"
 
+DEPENDENCIES=(
+  npx
+  rsync
+)
+
+for DEPENDENCY in "${DEPENDENCIES[@]}"; do
+  if ! command -v "$DEPENDENCY" > /dev/null; then
+    >&2 echo "Error: \"$DEPENDENCY\" is not installed."
+    exit 1
+  fi
+done
+
 APP_TEMPLATE_FILES_DIR=$(mktemp --directory)
 
 npx degit "${ARGS[IDENTIFIER]}" "$APP_TEMPLATE_FILES_DIR"
diff --git a/bin/rsync-mirror-local b/bin/rsync-mirror-local
--- a/bin/rsync-mirror-local
+++ b/bin/rsync-mirror-local
@@ -49,6 +49,17 @@ Options:
 EOF
 )"
 
+DEPENDENCIES=(
+  rsync
+)
+
+for DEPENDENCY in "${DEPENDENCIES[@]}"; do
+  if ! command -v "$DEPENDENCY" > /dev/null; then
+    >&2 echo "Error: \"$DEPENDENCY\" is not installed."
+    exit 1
+  fi
+done
+
 SOURCE_WITH_NO_TRAILING_SLASH=${ARGS[SOURCE]%/}
 TARGET_WITH_NO_TRAILING_SLASH=${ARGS[TARGET]%/}
 
diff --git a/bin/whomail b/bin/whomail
--- a/bin/whomail
+++ b/bin/whomail
@@ -48,4 +48,15 @@ Options:
 EOF
 )"
 
+DEPENDENCIES=(
+  whois
+)
+
+for DEPENDENCY in "${DEPENDENCIES[@]}"; do
+  if ! command -v "$DEPENDENCY" > /dev/null; then
+    >&2 echo "Error: \"$DEPENDENCY\" is not installed."
+    exit 1
+  fi
+done
+
 whois "${ARGS[DOMAIN]}" | grep --color=never @ | trim | sort | uniq
