bin: Make indent size configurable in indent

diff --git a/bin/indent b/bin/indent
--- a/bin/indent
+++ b/bin/indent
@@ -30,10 +30,10 @@ set -euo pipefail
 COMMAND_NAME=$(basename "$0")
 
 eval "$(docopts --help=- -A ARGS : "$@" <<EOF
-Indent text with four spaces.
+Indent input with spaces.
 
 Usage:
-  $COMMAND_NAME [FILE]
+  $COMMAND_NAME [--size SIZE] [FILE]
   $COMMAND_NAME -h | --help
 
 Examples:
@@ -41,19 +41,31 @@ Examples:
   cal | $COMMAND_NAME
 
 Options:
+  -s SIZE, --size SIZE
+      The number of spaces to indent input with [default: 4]
   -h, --help
       Show this documentation
 
-This command may appear to strip color from stdin, but it doesn't. Rather, many
-programs disable color output when stdout is not a tty, like when stdout is
-piped. This can be confirmed by indenting text from a command that is forced to
-use color, as in the following example:
+This command may appear to strip color from input, but it doesn't. Rather, many
+programs disable color output when output is sent to a piped program. This can
+be confirmed by indenting text from a command that is forced to use color, as in
+the following example:
 
   grep --color=always source "\$HOME/.bashrc" | $COMMAND_NAME
 EOF
 )"
 
+if (( ${ARGS[--size]} < 0 )); then
+  >&2 echo 'Error: Indent size must be non-negative.'
+  exit 1
+fi
+
+SPACES=''
+for (( I=1; I <= ${ARGS[--size]}; I++ )); do
+  SPACES+=' '
+done
+
 FILE_OR_STDIN=${ARGS[FILE]:-/dev/stdin}
 
 # https://unix.stackexchange.com/a/148111
-sed 's/^/    /' "$FILE_OR_STDIN"
+sed "s/^/$SPACES/" "$FILE_OR_STDIN"
