vcsh: Revert to using sudo in setup script
The Homebrew installer uses the "sudo" command and cannot be run as the
root user.

Many of the recent changes to the setup script were made to be able to
run the setup script as the root user without the "sudo" command being
installed. Now that it's clear the "sudo" command needs to be installed
anyway, we might as well require it, and that makes the rest of the
setup scripts simpler.

This was a good learning experience, though. Occasionally frustrating,
but good.

diff --git a/bin/personal/vcsh/dotfiles-openjck-setup b/bin/personal/vcsh/dotfiles-openjck-setup
--- a/bin/personal/vcsh/dotfiles-openjck-setup
+++ b/bin/personal/vcsh/dotfiles-openjck-setup
@@ -17,11 +17,6 @@
 # http://redsymbol.net/articles/unofficial-bash-strict-mode/
 set -euo pipefail
 
-if (( EUID != 0 )); then
-  >&2 echo 'FATAL ERROR: This script must be run as root.'
-  exit 1
-fi
-
 function os_is_debian_based() {
   [[ -f /etc/debian_version ]]
 }
@@ -31,25 +26,22 @@ if ! os_is_debian_based; then
   exit 1
 fi
 
-# https://stackoverflow.com/a/246128/715866
-THIS_SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
+if ! sudo -v; then
+  >&2 echo "FATAL ERROR: \"sudo\" must be installed and enabled for \"$USER\"."
+  exit 1
+fi
 
 # Install pip if it's not already installed.
 #
 # pip is needed to install uv, and uv is needed to run the setup script.
 if ! command -v pip > /dev/null; then
   if os_is_debian_based; then
-    apt-get install --assume-yes pipx
+    sudo apt-get install --assume-yes pipx
   fi
 fi
 
-# Install uv in the root user's account if it's not already installed.
 if ! command -v uv > /dev/null; then
   pipx install uv
 fi
 
-# pipx installs uv to /root/.local/bin/uv, so /root/.local/bin must be in the
-# PATH when running the main setup script. On some systems, it's not on the PATH
-# by default.
-PATH="/root/.local/bin:$PATH" \
-  "$THIS_SCRIPT_DIR"/dotfiles-openjck-setup-main/dotfiles-openjck-setup-main.py
+"$HOME"/bin/personal/vcsh/dotfiles-openjck-setup-main/dotfiles-openjck-setup-main.py
