bin, Bash: Format all files with latest shfmt
I actually don't like this change at all, and it's not configurable, but
it's not a big enough deal for me to avoid it.

diff --git a/bin/general/create-script b/bin/general/create-script
--- a/bin/general/create-script
+++ b/bin/general/create-script
@@ -58,13 +58,13 @@ for DEPENDENCY in "${DEPENDENCIES[@]}"; do
 done
 
 if ((${#MISSING_DEPENDENCIES[@]} > 0)); then
-  >&2 fold --spaces <<EOF
+  fold >&2 --spaces <<EOF
 FATAL ERROR: The following are not installed. You must install them on your \
 own for "$COMMAND_NAME" to function properly.
 
 EOF
   for DEPENDENCY in "${MISSING_DEPENDENCIES[@]}"; do
-    >&2 echo "  - $DEPENDENCY"
+    echo >&2 "  - $DEPENDENCY"
   done
   exit 1
 fi
@@ -98,7 +98,7 @@ EOF
 )"
 
 if [[ -f ${ARGS[FILE]} ]]; then
-  >&2 echo "FATAL ERROR: File \"${ARGS[FILE]}\" already exists."
+  echo >&2 "FATAL ERROR: File \"${ARGS[FILE]}\" already exists."
   exit 1
 fi
 
diff --git a/bin/general/device b/bin/general/device
--- a/bin/general/device
+++ b/bin/general/device
@@ -58,13 +58,13 @@ for DEPENDENCY in "${DEPENDENCIES[@]}"; do
 done
 
 if ((${#MISSING_DEPENDENCIES[@]} > 0)); then
-  >&2 fold --spaces <<EOF
+  fold >&2 --spaces <<EOF
 FATAL ERROR: The following are not installed. You must install them on your \
 own for "$COMMAND_NAME" to function properly.
 
 EOF
   for DEPENDENCY in "${MISSING_DEPENDENCIES[@]}"; do
-    >&2 echo "  - $DEPENDENCY"
+    echo >&2 "  - $DEPENDENCY"
   done
   exit 1
 fi
@@ -93,6 +93,6 @@ EOF
 if OUTPUT=$(findmnt --noheadings --output SOURCE --mountpoint "${ARGS[MOUNTPOINT]}"); then
   echo "$OUTPUT"
 else
-  >&2 echo "FATAL ERROR: ${ARGS[MOUNTPOINT]} is not a mountpoint."
+  echo >&2 "FATAL ERROR: ${ARGS[MOUNTPOINT]} is not a mountpoint."
   exit 1
 fi
diff --git a/bin/general/repl b/bin/general/repl
--- a/bin/general/repl
+++ b/bin/general/repl
@@ -58,13 +58,13 @@ for DEPENDENCY in "${DEPENDENCIES[@]}"; do
 done
 
 if ((${#MISSING_DEPENDENCIES[@]} > 0)); then
-  >&2 fold --spaces <<EOF
+  fold >&2 --spaces <<EOF
 FATAL ERROR: The following are not installed. You must install them on your \
 own for "$COMMAND_NAME" to function properly.
 
 EOF
   for DEPENDENCY in "${MISSING_DEPENDENCIES[@]}"; do
-    >&2 echo "  - $DEPENDENCY"
+    echo >&2 "  - $DEPENDENCY"
   done
   exit 1
 fi
@@ -109,7 +109,7 @@ function exit_if_not_installed() {
   local COMMAND=$1
 
   if ! command -v "$COMMAND" >/dev/null; then
-    >&2 echo "FATAL ERROR: \"$COMMAND\" is not installed."
+    echo >&2 "FATAL ERROR: \"$COMMAND\" is not installed."
     exit 1
   fi
 }
@@ -142,7 +142,7 @@ case "${ARGS[IDENTIFIER]}" in
     exec irb
     ;;
   *)
-    >&2 echo "FATAL ERROR: Identifier \"${ARGS[IDENTIFIER]}\" not supported."
+    echo >&2 "FATAL ERROR: Identifier \"${ARGS[IDENTIFIER]}\" not supported."
     exit 1
     ;;
 esac
diff --git a/bin/personal/vcsh/dotfiles-openjck-setup-bootstrap b/bin/personal/vcsh/dotfiles-openjck-setup-bootstrap
--- a/bin/personal/vcsh/dotfiles-openjck-setup-bootstrap
+++ b/bin/personal/vcsh/dotfiles-openjck-setup-bootstrap
@@ -67,7 +67,7 @@ elif [[ $DISTRO == fedora ]]; then
 fi
 
 if [[ $SUPPORTED == false ]]; then
-  >&2 echo 'FATAL ERROR: This distro is not supported.'
+  echo >&2 'FATAL ERROR: This distro is not supported.'
   exit 1
 fi
 
@@ -76,7 +76,7 @@ fi
 # process, so that they don't need to be prompted for it in the middle of this
 # process.
 if ! sudo --validate; then
-  >&2 echo "FATAL ERROR: \"sudo\" must be installed and enabled for \"$USER\"."
+  echo >&2 "FATAL ERROR: \"sudo\" must be installed and enabled for \"$USER\"."
   exit 1
 fi
 
